name: Deploy Frontend to Firebase

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'  # only trigger if frontend files change

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build and Deploy
        run: |
          cd frontend
          npm ci
          npm run build
          firebase deploy --project ${{ secrets.FIREBASE_PROJECT_ID }} --token "$FIREBASE_TOKEN" --only hosting
